// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeretanaApp.Models;

namespace TeretanaApp.Migrations
{
    [DbContext(typeof(ContextKlasa))]
    partial class ContextKlasaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("TeretanaApp.Models.Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GodinaRodjenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeretanaId")
                        .HasColumnType("int");

                    b.Property<double>("Tezina")
                        .HasColumnType("float");

                    b.Property<int>("Visina")
                        .HasColumnType("int");

                    b.HasKey("ClanId");

                    b.HasIndex("TeretanaId");

                    b.ToTable("Clanovi");
                });

            modelBuilder.Entity("TeretanaApp.Models.Radnik", b =>
                {
                    b.Property<int>("RadnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GodinaRodjenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeretanaId")
                        .HasColumnType("int");

                    b.HasKey("RadnikId");

                    b.HasIndex("TeretanaId");

                    b.ToTable("Radnici");
                });

            modelBuilder.Entity("TeretanaApp.Models.Teretana", b =>
                {
                    b.Property<int>("TeretanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeretanaId");

                    b.ToTable("Teretane");
                });

            modelBuilder.Entity("TeretanaApp.Models.Clan", b =>
                {
                    b.HasOne("TeretanaApp.Models.Teretana", "Teretana")
                        .WithMany("Clan")
                        .HasForeignKey("TeretanaId");

                    b.Navigation("Teretana");
                });

            modelBuilder.Entity("TeretanaApp.Models.Radnik", b =>
                {
                    b.HasOne("TeretanaApp.Models.Teretana", "Teretana")
                        .WithMany("Radnik")
                        .HasForeignKey("TeretanaId");

                    b.Navigation("Teretana");
                });

            modelBuilder.Entity("TeretanaApp.Models.Teretana", b =>
                {
                    b.Navigation("Clan");

                    b.Navigation("Radnik");
                });
#pragma warning restore 612, 618
        }
    }
}
